development:
  adapter: sqlite3
  database: nadya.sqlite
  pool: 5 
  timeout: 5000
# test:
#   adapter: mysql
#   database: library_test
#   username: root
#   password: 
#   host: localhost
production:
  adapter: postgresql
  database: karavell_karav85
  username: karavell_karav85
  password: zDkz57Rao6iUGCJ4__
  host: postgresql0.locum.ru
  encoding: utf8