development:
  adapter: mysql
  database: library_development
  username: root
  password: 
  host: localhost
test:
  adapter: mysql
  database: library_test
  username: root
  password: 
  host: localhost
production:
  adapter: mysql
  database: karavell_karav65
  username: karavell_karav65
  password: vnLlWAgU
  host: mysql0.locum.ru